### ISSUE TITLE
Use GTFS bus feeds

### ISSUE THREAD

**Issue by Katsute** [KatsuteDev/OneMTA#100]
### Feature

Use GTFS feeds for bus rather than json

<http://bt.mta.info/wiki/Developers/GTFSRt>

### Reason

GTFS is far more efficient than raw json requests.

**Comment by Katsute** [comment]
@mashiro-san create a new branch gtfs-bus

**Comment by ghost** [comment]
@Katsute I have created a new branch `gtfs-bus@f3f2dcd`

**Comment by Katsute** [comment]
@mashiro-san create new orphan branch reference

**Comment by ghost** [comment]
@Katsute I have created a new orphan branch `reference`
