### ISSUE TITLE
Arrival/departure time is incorrect

### ISSUE THREAD

**Issue by Katsute** [KatsuteDev/OneMTA#23]
### Prerequisites

- [X] I have checked that no other similar issue already exists.
- [X] I have checked that this issue is actually a bug and not a feature.
- [X] I have checked [discussions](https://github.com/KatsuteDev/OneMTA/discussions).
- [X] I have checked the [documentation](https://docs.katsute.dev/onemta).

### Operating System

Windows 10

### Java Version

Java 17

### Release Version

1.0.1

### Issue

Arrival/departure times are incorrect, code is expecting epoch to be in milliseconds while gtfs returns epoch in seconds. Fix this by multiplying the time by 1000.

https://github.com/KatsuteDev/OneMTA/blob/130f96254e7f8140c495187546345fe148072272/src/main/java/dev/katsute/onemta/MTASchema_Subway.java#L470-L471

https://github.com/KatsuteDev/OneMTA/blob/130f96254e7f8140c495187546345fe148072272/src/main/java/dev/katsute/onemta/MTASchema_LIRR.java#L478-L479

https://github.com/KatsuteDev/OneMTA/blob/130f96254e7f8140c495187546345fe148072272/src/main/java/dev/katsute/onemta/MTASchema_MNR.java#L434-L435

**Comment by Katsute** [comment]
@sinon-bot branch fix gtfs time

**Comment by ghost** [comment]
New branch created `fix-gtfs-time@130f962`

<sub>This branch was created by @Katsute.</sub>
