### ISSUE TITLE
Add support for station transfer data

### ISSUE THREAD

**Issue by Katsute** [KatsuteDev/OneMTA#24]
### Prerequisites

- [X] I have checked that no other similar feature request already exists.
- [X] I have checked [discussions](https://github.com/KatsuteDev/OneMTA/discussions).
- [X] This feature request makes sense for the project.
- [X] I have checked that this feature does not already exist.
- [X] I am running the latest release version.

### Feature

Add support for station transfer information. Keys are non-unique, csv parser may need to be altered.

Sample csv:

```csv
from_stop_id,to_stop_id,transfer_type,min_transfer_time
101,101,2,180
103,103,2,180
104,104,2,180
106,106,2,180
107,107,2,180
```

This method might need to be updated:

https://github.com/KatsuteDev/OneMTA/blob/130f96254e7f8140c495187546345fe148072272/src/main/java/dev/katsute/onemta/CSV.java#L69-L76

### Reason

Developers may want transfer information.

**Comment by Katsute** [comment]
@sinon-bot obranch reference

**Comment by ghost** [comment]
New branch created `reference@61f6a85`

<sub>This branch was created by @Katsute.</sub>

**Comment by Katsute** [comment]
Add method to stop `getTransfers()` that returns an array of stops. Only generate the array when requested the first time, keep null or use existing to prevent infinite loop.

**Comment by Katsute** [comment]
Do not include self as a valid transfer stop. Most dual platform stations do not have transfer walkways, only paid street transfers.

**Comment by Katsute** [comment]
@sinon-bot branch transfer

**Comment by ghost** [comment]
New branch created `transfer@44b47de`

<sub>This branch was created by @Katsute.</sub>
