### ISSUE TITLE
Add method to refresh realtime data

### ISSUE THREAD

**Issue by Katsute** [KatsuteDev/OneMTA#25]
### Prerequisites

- [X] I have checked that no other similar feature request already exists.
- [X] I have checked [discussions](https://github.com/KatsuteDev/OneMTA/discussions).
- [X] This feature request makes sense for the project.
- [X] I have checked that this feature does not already exist.
- [X] I am running the latest release version.

### Feature

Add a new method `.update(inplace?)` to stop, route, and vehicle objects; to allow developers to refresh realtime data without having to make new calls.

The `inplace` parameter should be false by default and return a new object to prevent developers from accidentally changing objects that are in use by other concurrent operations.

### Reason

Prevent redundant calls to the base object and to reduce confusion for developers expecting the realtime data to update everytime they make a call.

**Comment by Katsute** [comment]
Possibly add internal interface method `init()` to initialize and update objects, rather than seting the value directly on the variable and instantiation.

This could open the door to using protected/package-private initializers.

ex: instead of copying and pasting the static route initialization across all route implementations, use a single initializer `RouteSchema#init(Route route)` and set the values using `route.??? = ???`

https://github.com/KatsuteDev/OneMTA/blob/efe23fe82d3cb207f939c75230afe610b8d978be/src/main/java/dev/katsute/onemta/MTASchema_Bus.java#L107-L114

vs

```java
protected final String routeID = id;
  
protected final String routeShortName; 
protected final String routeLongName; 
protected final String routeDesc; 
  
protected final String routeColor; 
protected final String routeTextColor;
```
```java
protected final void init(Route route){
   route.routeShortName = row.get(csv.getHeaderIndex("route_short_name"));
   ...
}
```

**Comment by Katsute** [comment]
Only realtime data should be updated, static data should be final. Any arrays should also be regenerated and reassigned, don't update existing arrays.

**Comment by Katsute** [comment]
First comment method can't be used, protected variables in abstract is not allowed.

Instead move update method to the alerts and vehicles array method. Have optional param `update?` to determine if class should regenerated arrays, rather than using existing; again use new array, do not update old one.

**Comment by Katsute** [comment]
@sinon-bot branch refresh

**Comment by ghost** [comment]
New branch created `refresh@efe23fe`

<sub>This branch was created by @Katsute.</sub>
