### ISSUE TITLE
Add method to check if subway is express

### ISSUE THREAD

**Issue by Katsute** [KatsuteDev/OneMTA#29]
### Prerequisites

- [X] I have checked that no other similar feature request already exists.
- [X] I have checked [discussions](https://github.com/KatsuteDev/OneMTA/discussions).
- [X] This feature request makes sense for the project.
- [X] I have checked that this feature does not already exist.
- [X] I am running the latest release version.

### Feature

Add method to subway vehicles to check if they are express.

Achieved by checking the route ID of the trip, express routes will end with an `x`.

Local example: `7`
Express example: `7X`

### Reason

Subway express statuses are a commonly requested field

**Comment by Katsute** [comment]
@sinon-bot branch express

**Comment by ghost** [comment]
New branch created `express@21027fb`

<sub>This branch was created by @Katsute.</sub>
