### ISSUE TITLE
Alert start/end periods are incorrect

### ISSUE THREAD

**Issue by Katsute** [KatsuteDev/OneMTA#30]
### Prerequisites

- [X] I have checked that no other similar issue already exists.
- [X] I have checked that this issue is actually a bug and not a feature.
- [X] I have checked [discussions](https://github.com/KatsuteDev/OneMTA/discussions).
- [X] I have checked the [documentation](https://docs.katsute.dev/onemta).

### Operating System

Windows 10

### Java Version

Java 17

### Release Version

1.0.2

### Issue

Same issue as #23, multiply this time number by 1000 to fix it.

https://github.com/KatsuteDev/OneMTA/blob/e5e80dc8a4cfd5d1654c9bd1a093b7c82748dbbc/src/main/java/dev/katsute/onemta/MTASchema.java#L83-L84

**Comment by Katsute** [comment]
@sinon-bot branch fix gtfs alert time

**Comment by ghost** [comment]
New branch created `fix-gtfs-alert-time@21027fb`

<sub>This branch was created by @Katsute.</sub>
