### ISSUE TITLE
Utility methods

### ISSUE THREAD

**Issue by Katsute** [KatsuteDev/OneMTA#35]
### Prerequisites

- [X] I have checked that no other similar feature request already exists.
- [X] I have checked [discussions](https://github.com/KatsuteDev/OneMTA/discussions).
- [X] This feature request makes sense for the project.
- [X] I have checked that this feature does not already exist.
- [X] I am running the latest release version.

### Feature

Provide utility methods for:
 - Checking if stops are exactly the same
 - Checking if bi-directional stops are the same main stop
 - Checking if express and non-express routes are the same route
 - Utility method for stop/route formatting for N/S/Express

Should be an interface class with:
 - `.isExactStop()` || `.isExactRoute()`
 - `.isSameStop()` || `.isSameRoute()`

### Reason

Simplify equality checking.

**Comment by Katsute** [comment]
@sinon-bot branch utility

**Comment by ghost** [comment]
New branch created `utility@cbb3ab0`

<sub>This branch was created by @Katsute.</sub>
