### ISSUE TITLE
Invalid LineRef for Bus Company

### ISSUE THREAD

**Issue by Katsute** [KatsuteDev/OneMTA#37]
### Prerequisites

- [X] I have checked that no other similar issue already exists.
- [X] I have checked that this issue is actually a bug and not a feature.
- [X] I have checked [discussions](https://github.com/KatsuteDev/OneMTA/discussions).
- [X] I have checked the [documentation](https://docs.katsute.dev/onemta).

### Operating System

Windows 10

### Java Version

Java 17

### Release Version

1.1.0-SNAPSHOT

### Issue

Busses under Bus Company use the `LineRef`: `MTABC_` not `MTA NYCT_`

https://github.com/KatsuteDev/OneMTA/blob/5e15ad6976cce8d2f40037f3e7f57bb7aa4ca42b/src/main/java/dev/katsute/onemta/MTAService.java#L71

https://github.com/KatsuteDev/OneMTA/blob/3e9b1c459b24aedf3528698bce1b16e956f40c95/src/main/java/dev/katsute/onemta/MTASchema_Bus.java#L437

The code needs to internally run a check if the Bus Company static data is used, and adjust the `LineRef` accordingly.

**Comment by Katsute** [comment]
@sinon-bot branch bc-lineref

**Comment by ghost** [comment]
New branch created `bc-lineref@5fe5e97`

<sub>This branch was created by @Katsute.</sub>
