### ISSUE TITLE
Update tests causing issues

### ISSUE THREAD

**Issue by Katsute** [KatsuteDev/OneMTA#40]
### Prerequisites

- [X] I have checked that no other similar issue already exists.
- [X] I have checked that this issue is actually a bug and not a feature.
- [X] I have checked [discussions](https://github.com/KatsuteDev/OneMTA/discussions).
- [X] I have checked the [documentation](https://docs.katsute.dev/onemta).

### Operating System

ubuntu-latest

### Java Version

Java 8, 11, 17

### Release Version

1.1.0-SNAPSHOT

### Issue

Using the update method causes some tests to fail, particularly vehicles. Change the update tests so it updates a new instance, rather than the one pregenerated for the test case.

**Comment by Katsute** [comment]
@sinon-bot branch fix-tests

**Comment by ghost** [comment]
New branch created `fix-tests@e5b1436`

<sub>This branch was created by @Katsute.</sub>
