### ISSUE TITLE
Cancelled Trip API

### ISSUE THREAD

**Issue by Katsute** [KatsuteDev/OneMTA#51]
### Prerequisites

- [X] I have checked that no other similar feature request already exists.
- [X] I have checked [discussions](https://github.com/KatsuteDev/OneMTA/discussions).
- [X] This feature request makes sense for the project.
- [X] I have checked that this feature does not already exist.
- [X] I am running the latest release version.

### Feature

The MTA SIRI Bus API has received an update: https://bustime.mta.info/wiki/Developers/CancelledTripAPIFeatures

||Without Cancelled Trip Information|With Cancelled Trip Information|
|:-:|:-:|:-:|
|v1|`/api/siri/stop-monitoring.xml`|`/api/2/siri/stop-monitoring.xml`|
|v2|`/api/siri/stop-monitoring.xml?version=2`|`/api/2/siri/stop-monitoring.xml?version=2`|

### Stop-monitoring output

```diff
<MonitoredVehicleJourney>
  <MonitoredStopVisit>
--    <MonitoredCall>
--      <ArrivalStatus>cancelled</ArrivalStatus>
--      <DepartureStatus>cancelled</DepartureStatus>
--    </MonitoredCall>
++  <MonitoredVehicleJourney>
++      <VehicleStatus>cancelled</VehicleStatus>
++  </MonitoredVehicleJourney>
  </MonitoredStopVisit>
</MonitoredVehicleJourney>
```

### Alert Support

```gtfs
 entity {
  id: "MTA NYCT_GH_A2-Weekday-SDon-063200_BX39_765"
  alert {
    informed_entity {
      agency_id: "MTA NYCT"
      trip {
        route_id: "BX39"
        direction_id: 0
      }
    }
    informed_entity {
      agency_id: "MTA NYCT"
      trip {
        route_id: "BX39"
        direction_id: 1
      }
    }
    effect: REDUCED_SERVICE
    description_text {
      translation {
        text: "The 10:32am BX39 to SOUNDVIEW AV/CORNELL AV is canceled"
        language: "EN"
      }
    }
  }
}
```

### Reason

Required to keep up to date with API.

**Comment by Katsute** [comment]
@sinon-bot branch canceled

**Comment by ghost** [comment]
#### *️⃣ Branch Created

New branch created `canceled@f42fd05`

<sub>This branch was created by @Katsute.</sub>
