### ISSUE TITLE
Document enums

### ISSUE THREAD

**Issue by Katsute** [KatsuteDev/OneMTA#60]
### Prerequisites

- [X] I have checked that no other similar feature request already exists.
- [X] I have checked [discussions](https://github.com/KatsuteDev/OneMTA/discussions).
- [X] This feature request makes sense for the project.
- [X] I have checked that this feature does not already exist.
- [X] I am running the latest release version.

### Feature

For methods that return enums as strings, use `@see` pointing towards the enum in the GTFS library.

### Reason

Allow developers to easily see what string values can be returned.

**Comment by Katsute** [comment]
<https://cs.github.com/KatsuteDev/OneMTA?q=.name()%20language%3AJava>

**Comment by Katsute** [comment]
@mashiro-san create a branch document enums

**Comment by ghost** [comment]
@Katsute I have created a new branch [`document-enums@fa8b91a`](https://github.com/KatsuteDev/OneMTA/tree/document-enums@fa8b91a)

**Comment by Katsute** [comment]
Could not implement, documentation for enums is in a vendored file and docs are only for public files.
