### ISSUE TITLE
(internal) zip changes for MTA bus static data

### ISSUE THREAD

**Issue by Katsute** [KatsuteDev/OneMTA#62]
**This issue ticket is for internal tracking, developers please refer to issue [#61](https://github.com/KatsuteDev/OneMTA/issues/61).**

---

Bus data is served in a folder within the zip, rather than the base directory. The below section needs to be modified to reflect this change.

https://github.com/KatsuteDev/OneMTA/blob/f1e627bd18bd1f34384dd37a228915fc56c3164e/src/main/java/dev/katsute/onemta/DataResource.java#L76-L88

**Comment by Katsute** [comment]
Use try catch to preserve current behavior, if failed then iterate through all folders to find the data.

**Comment by Katsute** [comment]
Optionally accept a parameter for the path to the folder.

**Comment by Katsute** [comment]
@mashiro-san please create a branch dynamic zip

**Comment by ghost** [comment]
@Katsute I have created a new branch [`dynamic-zip@f1e627b`](https://github.com/KatsuteDev/OneMTA/tree/dynamic-zip@f1e627b)

**Comment by Katsute** [comment]
<https://stackoverflow.com/a/54031491>
