### ISSUE TITLE
Use all bus data

### ISSUE THREAD

**Issue by Katsute** [KatsuteDev/OneMTA#84]
### Feature

Anytime a bus is requested:

1. Check the cache
2. Pull data for **all** busses
3. Parse
4. Fulfill the request

### Reason

Current implementation runs a new request for every bus which is not efficient for enterprise. Requesting all busses then parsing is more efficient when submitting multiple requests.

**Comment by Katsute** [comment]
Store results by line to optimize queries rather than iterating through everything.

**Comment by Katsute** [comment]
~~Use similar binary search implemented in #90 against bus line~~ not possible

Store raw data in cache, DO NOT STORE OBJECTS; will cause memory issues.

< 10,000 busses

<https://bt.mta.info/wiki/Developers/SIRIVehicleMonitoring>

> Please note that the calls made without either a VehicleRef or LineRef produces quite a load on the system, so use them sparingly. Any developers found to be making repeated calls (e.g. at less than  30 second intervals) for all vehicles in the system may find their key revoked.

**Comment by Katsute** [comment]
Only this subclass needs to be modified

https://github.com/KatsuteDev/OneMTA/blob/f3dfe303d9a7dd1b365b582b32113d776a549bb5/src/main/java/dev/katsute/onemta/MTAService.java#L52

Stop monitoring should derive values from vehicle request if possible.

**Comment by Katsute** [comment]
JSON parser needs to be massively optimized to avoid memory issues; use JIT (just-in-time) parsing, where we load immediate keys into memory, then parse the subsequent object when requested.


___

~~This count needs to be optimized to only run once:~~ not possible due to split logic

https://github.com/KatsuteDev/OneMTA/blob/f3dfe303d9a7dd1b365b582b32113d776a549bb5/src/main/java/dev/katsute/onemta/Json.java#L129

<https://sites.google.com/site/gson/streaming>

<https://stackoverflow.com/a/11876086>

Regex may actually be more inefficient since we are rescanning the string multiple times. Use character loop stream instead.

___

Return a method to parse for:

https://github.com/KatsuteDev/OneMTA/blob/f3dfe303d9a7dd1b365b582b32113d776a549bb5/src/main/java/dev/katsute/onemta/Json.java#L197-L200

and

https://github.com/KatsuteDev/OneMTA/blob/f3dfe303d9a7dd1b365b582b32113d776a549bb5/src/main/java/dev/katsute/onemta/Json.java#L235-L238

**Comment by Katsute** [comment]
@mashiro-san create a branch upgrade-json

**Comment by ghost** [comment]
@Katsute I have created a new branch `upgrade-json@f3dfe30`

**Comment by Katsute** [comment]
- get methods need to be optimized so synchronized isn't blocking threads
- pull bus stop alert info from gtfs feed
- derive stop vehicles from all vehicles

**Comment by Katsute** [comment]
Use [CopyOnWriteArrayList](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CopyOnWriteArrayList.html) to allow concurrent reads and locked writes.

[ConcurrentMap](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentMap.html)?

In order to make write thread safe, have synchronized write block also check if its expired before fetching (any current active writes will make the result not expired, any queued writes will see that the resource is no longer expired and will return the new one instead).

Get first then check if expired to prevent concurrency issues.

**Comment by Katsute** [comment]
@mashiro-san create a new branch upgrade cache

**Comment by ghost** [comment]
@Katsute I have created a new branch `upgrade-cache@ebf9c8e`

**Comment by Katsute** [comment]
Possibly use #100 to implement this.
