### ISSUE TITLE
Failing to `resolveSubwayFeed` on express routes

### ISSUE THREAD

**Issue by Katsute** [KatsuteDev/OneMTA#96]
Missing `~X` routes

https://github.com/KatsuteDev/OneMTA/blob/ebf9c8e44cda6c8a9601d51d648d4e56f124c9d8/src/main/java/dev/katsute/onemta/MTAImpl.java#L115-L154

**Comment by Katsute** [comment]
@mashiro-san create a branch fix express

**Comment by ghost** [comment]
@Katsute I have created a new branch `fix-express@2497bb1`
